build:
  image: registry.gitlab.com/tezos/opam-repository:runtime-build-test-dependencies--fac36cdc1d0f64a6702907e777e396172dee1464
  script:
    - eval $(opam env)
    - opam depext --with-test
    - opam install --with-test --with-doc --deps-only .
    - opam clean
    - dune build
    - dune runtest
  cache:
    paths:
      - _build
      - _opam

wasm-build:
  image: emscripten/emsdk
  script:
    - apt update && apt install -y libgmp-dev opam lzip
    - cd src && ./build_wasm.sh
